# Noisy data file
filename_data : '\\wsl$\Ubuntu-20.04\home\aa\Documents\Data\Data_generator\SE2\noisy_data.mat'

filename_gt : '\\wsl$\Ubuntu-20.04\home\aa\Documents\Data\Data_generator\SE2\gt_SE2.mat'

# Initialization type. Options:
#   - odom (odometry)
#   - L-InEKF (Left-invariant EKF)
# init_method : 'L-InEkF'
init_method : 'odom'

# Gauss-Newton optimization parameters
optim_params:
  # Maximum number of iterations
  max_iterations  : 1e2

  # Normalized gradient stopping criterion. 
  #   The normalization is (norm( J' * (Sigma \ e))*norm(Sigma)) < tol
  tol_ngrad_stop         : 1e-6
  # Search direction stopping criterion
  tol_sdir_stop         : 1e-4

  # Armijo parameters
  armijo_beta           : 0.3
  armijo_c1             : 1e-6
  armijo_max_iteration  : 15

  # Can take 
  #   - 'qr'
  #   - 'chol'
  #   - '\'
  lin_solver            : '\'